# Generated by Django 3.1.6 on 2021-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='utilizada',
            field=models.BooleanField(default=False),
        ),
    ]
