# Generated by Django 3.1.6 on 2021-02-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_utilizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='utilizada',
        ),
    ]
